
import findKey from 'lodash/findKey';

const categories = {
  'Sans Serif': {
    'fallback': ['Helvetica', 'sans-serif'],
  },
  'Serif': {
    'fallback': ['Georgia', 'serif'],
  },
  'Handwriting': {
    'fallback': ['cursive'],
  },
  'Monospace': {
    'fallback': ['Courier New', 'Courier', 'monospace'],
  },
  'Display': {
    'fallback': ['fantasy'],
  },
};

export const fontsSafe = {
  'Arial': {
    'category': 'sans-serif',
    'fallback': ['Arial', 'Helvetica', 'sans-serif'],
  },
  'Arial Black': {
    'category': 'sans-serif',
    'fallback': ['Arial Black', 'Gadget', 'sans-serif'],
  },
  'Courier New': {
    'category': 'monospace',
    'fallback': ['Courier New', 'Courier', 'monospace'],
  },
  'Helvetica': {
    'category': 'sans-serif',
    'fallback': ['Helvetica', 'sans-serif'],
  },
  'Impact': {
    'category': 'sans-serif',
    'fallback': ['Impact', 'Charcoal', 'sans-serif'],
  },
  'Lucida': {
    'category': 'sans-serif',
    'fallback': ['Lucida Sans Unicode', 'Lucida Grande', 'sans-serif'],
  },
  'Palatino': {
    'category': 'sans-serif',
    'fallback': ['Palatino Linotype', 'Book Antiqua', 'Palatino', 'serif'],
  },
  'Tahoma': {
    'category': 'sans-serif',
    'fallback': ['Tahoma', 'Geneva', 'sans-serif'],
  },
  'Times New Roman': {
    'category': 'sans-serif',
    'fallback': ['Times New Roman', 'Times', 'sans-serif'],
  },
  'Verdana': {
    'category': 'sans-serif',
    'fallback': ['Verdana', 'Geneva', 'sans-serif'],
  },
};

export const fontsGoogle = {
  'ABeeZee': {'category': 'Sans Serif'},
  'Abel': {'category': 'Sans Serif'},
  'Abhaya Libre': {'category': 'Serif'},
  'Abril Fatface': {'category': 'Display'},
  'Aclonica': {'category': 'Sans Serif'},
  'Acme': {'category': 'Sans Serif'},
  'Actor': {'category': 'Sans Serif'},
  'Adamina': {'category': 'Serif'},
  'Advent Pro': {'category': 'Sans Serif'},
  'Aguafina Script': {'category': 'Handwriting'},
  'Akronim': {'category': 'Display'},
  'Aladin': {'category': 'Handwriting'},
  'Aldrich': {'category': 'Sans Serif'},
  'Alef': {'category': 'Sans Serif'},
  'Alegreya': {'category': 'Serif'},
  'Alegreya SC': {'category': 'Serif'},
  'Alegreya Sans': {'category': 'Sans Serif'},
  'Alegreya Sans SC': {'category': 'Sans Serif'},
  'Alex Brush': {'category': 'Handwriting'},
  'Alfa Slab One': {'category': 'Display'},
  'Alice': {'category': 'Serif'},
  'Alike': {'category': 'Serif'},
  'Alike Angular': {'category': 'Serif'},
  'Allan': {'category': 'Display'},
  'Allerta': {'category': 'Sans Serif'},
  'Allerta Stencil': {'category': 'Sans Serif'},
  'Allura': {'category': 'Handwriting'},
  'Almendra': {'category': 'Serif'},
  'Almendra Display': {'category': 'Display'},
  'Almendra SC': {'category': 'Serif'},
  'Amarante': {'category': 'Display'},
  'Amaranth': {'category': 'Sans Serif'},
  'Amatic SC': {'category': 'Handwriting'},
  'Amatica SC': {'category': 'Display'},
  'Amethysta': {'category': 'Serif'},
  'Amiko': {'category': 'Sans Serif'},
  'Amiri': {'category': 'Serif'},
  'Amita': {'category': 'Handwriting'},
  'Anaheim': {'category': 'Sans Serif'},
  'Andada': {'category': 'Serif'},
  'Andika': {'category': 'Sans Serif'},
  'Angkor': {'category': 'Display'},
  'Annie Use Your Telescope': {'category': 'Handwriting'},
  'Anonymous Pro': {'category': 'Monospace'},
  'Antic': {'category': 'Sans Serif'},
  'Antic Didone': {'category': 'Serif'},
  'Antic Slab': {'category': 'Serif'},
  'Anton': {'category': 'Sans Serif'},
  'Arapey': {'category': 'Serif'},
  'Arbutus': {'category': 'Display'},
  'Arbutus Slab': {'category': 'Serif'},
  'Architects Daughter': {'category': 'Handwriting'},
  'Archivo Black': {'category': 'Sans Serif'},
  'Archivo Narrow': {'category': 'Sans Serif'},
  'Aref Ruqaa': {'category': 'Serif'},
  'Arima Madurai': {'category': 'Display'},
  'Arimo': {'category': 'Sans Serif'},
  'Arizonia': {'category': 'Handwriting'},
  'Armata': {'category': 'Sans Serif'},
  'Arsenal': {'category': 'Sans Serif'},
  'Artifika': {'category': 'Serif'},
  'Arvo': {'category': 'Serif'},
  'Arya': {'category': 'Sans Serif'},
  'Asap': {'category': 'Sans Serif'},
  'Asar': {'category': 'Serif'},
  'Asset': {'category': 'Display'},
  'Assistant': {'category': 'Sans Serif'},
  'Astloch': {'category': 'Display'},
  'Asul': {'category': 'Sans Serif'},
  'Athiti': {'category': 'Sans Serif'},
  'Atma': {'category': 'Display'},
  'Atomic Age': {'category': 'Display'},
  'Aubrey': {'category': 'Display'},
  'Audiowide': {'category': 'Display'},
  'Autour One': {'category': 'Display'},
  'Average': {'category': 'Serif'},
  'Average Sans': {'category': 'Sans Serif'},
  'Averia Gruesa Libre': {'category': 'Display'},
  'Averia Libre': {'category': 'Display'},
  'Averia Sans Libre': {'category': 'Display'},
  'Averia Serif Libre': {'category': 'Display'},
  'Bad Script': {'category': 'Handwriting'},
  'Bahiana': {'category': 'Display'},
  'Baloo': {'category': 'Display'},
  'Baloo Bhai': {'category': 'Display'},
  'Baloo Bhaina': {'category': 'Display'},
  'Baloo Chettan': {'category': 'Display'},
  'Baloo Da': {'category': 'Display'},
  'Baloo Paaji': {'category': 'Display'},
  'Baloo Tamma': {'category': 'Display'},
  'Baloo Thambi': {'category': 'Display'},
  'Balthazar': {'category': 'Serif'},
  'Bangers': {'category': 'Display'},
  'Barrio': {'category': 'Display'},
  'Basic': {'category': 'Sans Serif'},
  'Battambang': {'category': 'Display'},
  'Baumans': {'category': 'Display'},
  'Bayon': {'category': 'Display'},
  'Belgrano': {'category': 'Serif'},
  'Belleza': {'category': 'Sans Serif'},
  'BenchNine': {'category': 'Sans Serif'},
  'Bentham': {'category': 'Serif'},
  'Berkshire Swash': {'category': 'Handwriting'},
  'Bevan': {'category': 'Display'},
  'Bigelow Rules': {'category': 'Display'},
  'Bigshot One': {'category': 'Display'},
  'Bilbo': {'category': 'Handwriting'},
  'Bilbo Swash Caps': {'category': 'Handwriting'},
  'BioRhyme': {'category': 'Serif'},
  'BioRhyme Expanded': {'category': 'Serif'},
  'Biryani': {'category': 'Sans Serif'},
  'Bitter': {'category': 'Serif'},
  'Black Ops One': {'category': 'Display'},
  'Bokor': {'category': 'Display'},
  'Bonbon': {'category': 'Handwriting'},
  'Boogaloo': {'category': 'Display'},
  'Bowlby One': {'category': 'Display'},
  'Bowlby One SC': {'category': 'Display'},
  'Brawler': {'category': 'Serif'},
  'Bree Serif': {'category': 'Serif'},
  'Bubblegum Sans': {'category': 'Display'},
  'Bubbler One': {'category': 'Sans Serif'},
  'Buda': {'category': 'Display'},
  'Buenard': {'category': 'Serif'},
  'Bungee': {'category': 'Display'},
  'Bungee Hairline': {'category': 'Display'},
  'Bungee Inline': {'category': 'Display'},
  'Bungee Outline': {'category': 'Display'},
  'Bungee Shade': {'category': 'Display'},
  'Butcherman': {'category': 'Display'},
  'Butterfly Kids': {'category': 'Handwriting'},
  'Cabin': {'category': 'Sans Serif'},
  'Cabin Condensed': {'category': 'Sans Serif'},
  'Cabin Sketch': {'category': 'Display'},
  'Caesar Dressing': {'category': 'Display'},
  'Cagliostro': {'category': 'Sans Serif'},
  'Cairo': {'category': 'Sans Serif'},
  'Calligraffitti': {'category': 'Handwriting'},
  'Cambay': {'category': 'Sans Serif'},
  'Cambo': {'category': 'Serif'},
  'Candal': {'category': 'Sans Serif'},
  'Cantarell': {'category': 'Sans Serif'},
  'Cantata One': {'category': 'Serif'},
  'Cantora One': {'category': 'Sans Serif'},
  'Capriola': {'category': 'Sans Serif'},
  'Cardo': {'category': 'Serif'},
  'Carme': {'category': 'Sans Serif'},
  'Carrois Gothic': {'category': 'Sans Serif'},
  'Carrois Gothic SC': {'category': 'Sans Serif'},
  'Carter One': {'category': 'Display'},
  'Catamaran': {'category': 'Sans Serif'},
  'Caudex': {'category': 'Serif'},
  'Caveat': {'category': 'Handwriting'},
  'Caveat Brush': {'category': 'Handwriting'},
  'Cedarville Cursive': {'category': 'Handwriting'},
  'Ceviche One': {'category': 'Display'},
  'Changa': {'category': 'Sans Serif'},
  'Changa One': {'category': 'Display'},
  'Chango': {'category': 'Display'},
  'Chathura': {'category': 'Sans Serif'},
  'Chau Philomene One': {'category': 'Sans Serif'},
  'Chela One': {'category': 'Display'},
  'Chelsea Market': {'category': 'Display'},
  'Chenla': {'category': 'Display'},
  'Cherry Cream Soda': {'category': 'Display'},
  'Cherry Swash': {'category': 'Display'},
  'Chewy': {'category': 'Display'},
  'Chicle': {'category': 'Display'},
  'Chivo': {'category': 'Sans Serif'},
  'Chonburi': {'category': 'Display'},
  'Cinzel': {'category': 'Serif'},
  'Cinzel Decorative': {'category': 'Display'},
  'Clicker Script': {'category': 'Handwriting'},
  'Coda': {'category': 'Display'},
  'Coda Caption': {'category': 'Sans Serif'},
  'Codystar': {'category': 'Display'},
  'Coiny': {'category': 'Display'},
  'Combo': {'category': 'Display'},
  'Comfortaa': {'category': 'Display'},
  'Coming Soon': {'category': 'Handwriting'},
  'Concert One': {'category': 'Display'},
  'Condiment': {'category': 'Handwriting'},
  'Content': {'category': 'Display'},
  'Contrail One': {'category': 'Display'},
  'Convergence': {'category': 'Sans Serif'},
  'Cookie': {'category': 'Handwriting'},
  'Copse': {'category': 'Serif'},
  'Corben': {'category': 'Display'},
  'Cormorant': {'category': 'Serif'},
  'Cormorant Garamond': {'category': 'Serif'},
  'Cormorant Infant': {'category': 'Serif'},
  'Cormorant SC': {'category': 'Serif'},
  'Cormorant Unicase': {'category': 'Serif'},
  'Cormorant Upright': {'category': 'Serif'},
  'Courgette': {'category': 'Handwriting'},
  'Cousine': {'category': 'Monospace'},
  'Coustard': {'category': 'Serif'},
  'Covered By Your Grace': {'category': 'Handwriting'},
  'Crafty Girls': {'category': 'Handwriting'},
  'Creepster': {'category': 'Display'},
  'Crete Round': {'category': 'Serif'},
  'Crimson Text': {'category': 'Serif'},
  'Croissant One': {'category': 'Display'},
  'Crushed': {'category': 'Display'},
  'Cuprum': {'category': 'Sans Serif'},
  'Cutive': {'category': 'Serif'},
  'Cutive Mono': {'category': 'Monospace'},
  'Damion': {'category': 'Handwriting'},
  'Dancing Script': {'category': 'Handwriting'},
  'Dangrek': {'category': 'Display'},
  'David Libre': {'category': 'Serif'},
  'Dawning of a New Day': {'category': 'Handwriting'},
  'Days One': {'category': 'Sans Serif'},
  'Dekko': {'category': 'Handwriting'},
  'Delius': {'category': 'Handwriting'},
  'Delius Swash Caps': {'category': 'Handwriting'},
  'Delius Unicase': {'category': 'Handwriting'},
  'Della Respira': {'category': 'Serif'},
  'Denk One': {'category': 'Sans Serif'},
  'Devonshire': {'category': 'Handwriting'},
  'Dhurjati': {'category': 'Sans Serif'},
  'Didact Gothic': {'category': 'Sans Serif'},
  'Diplomata': {'category': 'Display'},
  'Diplomata SC': {'category': 'Display'},
  'Domine': {'category': 'Serif'},
  'Donegal One': {'category': 'Serif'},
  'Doppio One': {'category': 'Sans Serif'},
  'Dorsa': {'category': 'Sans Serif'},
  'Dosis': {'category': 'Sans Serif'},
  'Dr Sugiyama': {'category': 'Handwriting'},
  'Droid Sans': {'category': 'Sans Serif'},
  'Droid Sans Mono': {'category': 'Monospace'},
  'Droid Serif': {'category': 'Serif'},
  'Duru Sans': {'category': 'Sans Serif'},
  'Dynalight': {'category': 'Display'},
  'EB Garamond': {'category': 'Serif'},
  'Eagle Lake': {'category': 'Handwriting'},
  'Eater': {'category': 'Display'},
  'Economica': {'category': 'Sans Serif'},
  'Eczar': {'category': 'Serif'},
  'Ek Mukta': {'category': 'Sans Serif'},
  'El Messiri': {'category': 'Sans Serif'},
  'Electrolize': {'category': 'Sans Serif'},
  'Elsie': {'category': 'Display'},
  'Elsie Swash Caps': {'category': 'Display'},
  'Emblema One': {'category': 'Display'},
  'Emilys Candy': {'category': 'Display'},
  'Engagement': {'category': 'Handwriting'},
  'Englebert': {'category': 'Sans Serif'},
  'Enriqueta': {'category': 'Serif'},
  'Erica One': {'category': 'Display'},
  'Esteban': {'category': 'Serif'},
  'Euphoria Script': {'category': 'Handwriting'},
  'Ewert': {'category': 'Display'},
  'Exo': {'category': 'Sans Serif'},
  'Exo 2': {'category': 'Sans Serif'},
  'Expletus Sans': {'category': 'Display'},
  'Fanwood Text': {'category': 'Serif'},
  'Farsan': {'category': 'Display'},
  'Fascinate': {'category': 'Display'},
  'Fascinate Inline': {'category': 'Display'},
  'Faster One': {'category': 'Display'},
  'Fasthand': {'category': 'Serif'},
  'Fauna One': {'category': 'Serif'},
  'Federant': {'category': 'Display'},
  'Federo': {'category': 'Sans Serif'},
  'Felipa': {'category': 'Handwriting'},
  'Fenix': {'category': 'Serif'},
  'Finger Paint': {'category': 'Display'},
  'Fira Mono': {'category': 'Monospace'},
  'Fira Sans': {'category': 'Sans Serif'},
  'Fira Sans Condensed': {'category': 'Sans Serif'},
  'Fira Sans Extra Condensed': {'category': 'Sans Serif'},
  'Fjalla One': {'category': 'Sans Serif'},
  'Fjord One': {'category': 'Serif'},
  'Flamenco': {'category': 'Display'},
  'Flavors': {'category': 'Display'},
  'Fondamento': {'category': 'Handwriting'},
  'Fontdiner Swanky': {'category': 'Display'},
  'Forum': {'category': 'Display'},
  'Francois One': {'category': 'Sans Serif'},
  'Frank Ruhl Libre': {'category': 'Sans Serif'},
  'Freckle Face': {'category': 'Display'},
  'Fredericka the Great': {'category': 'Display'},
  'Fredoka One': {'category': 'Display'},
  'Freehand': {'category': 'Display'},
  'Fresca': {'category': 'Sans Serif'},
  'Frijole': {'category': 'Display'},
  'Fruktur': {'category': 'Display'},
  'Fugaz One': {'category': 'Display'},
  'GFS Didot': {'category': 'Serif'},
  'GFS Neohellenic': {'category': 'Sans Serif'},
  'Gabriela': {'category': 'Serif'},
  'Gafata': {'category': 'Sans Serif'},
  'Galada': {'category': 'Display'},
  'Galdeano': {'category': 'Sans Serif'},
  'Galindo': {'category': 'Display'},
  'Gentium Basic': {'category': 'Serif'},
  'Gentium Book Basic': {'category': 'Serif'},
  'Geo': {'category': 'Sans Serif'},
  'Geostar': {'category': 'Display'},
  'Geostar Fill': {'category': 'Display'},
  'Germania One': {'category': 'Display'},
  'Gidugu': {'category': 'Sans Serif'},
  'Gilda Display': {'category': 'Serif'},
  'Give You Glory': {'category': 'Handwriting'},
  'Glass Antiqua': {'category': 'Display'},
  'Glegoo': {'category': 'Serif'},
  'Gloria Hallelujah': {'category': 'Handwriting'},
  'Goblin One': {'category': 'Display'},
  'Gochi Hand': {'category': 'Handwriting'},
  'Gorditas': {'category': 'Display'},
  'Goudy Bookletter 1911': {'category': 'Serif'},
  'Graduate': {'category': 'Display'},
  'Grand Hotel': {'category': 'Handwriting'},
  'Gravitas One': {'category': 'Display'},
  'Great Vibes': {'category': 'Handwriting'},
  'Griffy': {'category': 'Display'},
  'Gruppo': {'category': 'Display'},
  'Gudea': {'category': 'Sans Serif'},
  'Gurajada': {'category': 'Serif'},
  'Habibi': {'category': 'Serif'},
  'Halant': {'category': 'Serif'},
  'Hammersmith One': {'category': 'Sans Serif'},
  'Hanalei': {'category': 'Display'},
  'Hanalei Fill': {'category': 'Display'},
  'Handlee': {'category': 'Handwriting'},
  'Hanuman': {'category': 'Serif'},
  'Happy Monkey': {'category': 'Display'},
  'Harmattan': {'category': 'Sans Serif'},
  'Headland One': {'category': 'Serif'},
  'Heebo': {'category': 'Sans Serif'},
  'Henny Penny': {'category': 'Display'},
  'Herr Von Muellerhoff': {'category': 'Handwriting'},
  'Hind': {'category': 'Sans Serif'},
  'Hind Guntur': {'category': 'Sans Serif'},
  'Hind Madurai': {'category': 'Sans Serif'},
  'Hind Siliguri': {'category': 'Sans Serif'},
  'Hind Vadodara': {'category': 'Sans Serif'},
  'Holtwood One SC': {'category': 'Serif'},
  'Homemade Apple': {'category': 'Handwriting'},
  'Homenaje': {'category': 'Sans Serif'},
  'IM Fell DW Pica': {'category': 'Serif'},
  'IM Fell DW Pica SC': {'category': 'Serif'},
  'IM Fell Double Pica': {'category': 'Serif'},
  'IM Fell Double Pica SC': {'category': 'Serif'},
  'IM Fell English': {'category': 'Serif'},
  'IM Fell English SC': {'category': 'Serif'},
  'IM Fell French Canon': {'category': 'Serif'},
  'IM Fell French Canon SC': {'category': 'Serif'},
  'IM Fell Great Primer': {'category': 'Serif'},
  'IM Fell Great Primer SC': {'category': 'Serif'},
  'Iceberg': {'category': 'Display'},
  'Iceland': {'category': 'Display'},
  'Imprima': {'category': 'Sans Serif'},
  'Inconsolata': {'category': 'Monospace'},
  'Inder': {'category': 'Sans Serif'},
  'Indie Flower': {'category': 'Handwriting'},
  'Inika': {'category': 'Serif'},
  'Inknut Antiqua': {'category': 'Serif'},
  'Irish Grover': {'category': 'Display'},
  'Istok Web': {'category': 'Sans Serif'},
  'Italiana': {'category': 'Serif'},
  'Italianno': {'category': 'Handwriting'},
  'Itim': {'category': 'Handwriting'},
  'Jacques Francois': {'category': 'Serif'},
  'Jacques Francois Shadow': {'category': 'Display'},
  'Jaldi': {'category': 'Sans Serif'},
  'Jim Nightshade': {'category': 'Handwriting'},
  'Jockey One': {'category': 'Sans Serif'},
  'Jolly Lodger': {'category': 'Display'},
  'Jomhuria': {'category': 'Display'},
  'Josefin Sans': {'category': 'Sans Serif'},
  'Josefin Slab': {'category': 'Serif'},
  'Joti One': {'category': 'Display'},
  'Judson': {'category': 'Serif'},
  'Julee': {'category': 'Handwriting'},
  'Julius Sans One': {'category': 'Sans Serif'},
  'Junge': {'category': 'Serif'},
  'Jura': {'category': 'Sans Serif'},
  'Just Another Hand': {'category': 'Handwriting'},
  'Just Me Again Down Here': {'category': 'Handwriting'},
  'Kadwa': {'category': 'Serif'},
  'Kalam': {'category': 'Handwriting'},
  'Kameron': {'category': 'Serif'},
  'Kanit': {'category': 'Sans Serif'},
  'Kantumruy': {'category': 'Sans Serif'},
  'Karla': {'category': 'Sans Serif'},
  'Karma': {'category': 'Serif'},
  'Katibeh': {'category': 'Display'},
  'Kaushan Script': {'category': 'Handwriting'},
  'Kavivanar': {'category': 'Handwriting'},
  'Kavoon': {'category': 'Display'},
  'Kdam Thmor': {'category': 'Display'},
  'Keania One': {'category': 'Display'},
  'Kelly Slab': {'category': 'Display'},
  'Kenia': {'category': 'Display'},
  'Khand': {'category': 'Sans Serif'},
  'Khmer': {'category': 'Display'},
  'Khula': {'category': 'Sans Serif'},
  'Kite One': {'category': 'Sans Serif'},
  'Knewave': {'category': 'Display'},
  'Kotta One': {'category': 'Serif'},
  'Koulen': {'category': 'Display'},
  'Kranky': {'category': 'Display'},
  'Kreon': {'category': 'Serif'},
  'Kristi': {'category': 'Handwriting'},
  'Krona One': {'category': 'Sans Serif'},
  'Kumar One': {'category': 'Display'},
  'Kumar One Outline': {'category': 'Display'},
  'Kurale': {'category': 'Serif'},
  'La Belle Aurore': {'category': 'Handwriting'},
  'Laila': {'category': 'Serif'},
  'Lakki Reddy': {'category': 'Handwriting'},
  'Lalezar': {'category': 'Display'},
  'Lancelot': {'category': 'Display'},
  'Lateef': {'category': 'Handwriting'},
  'Lato': {'category': 'Sans Serif'},
  'League Script': {'category': 'Handwriting'},
  'Leckerli One': {'category': 'Handwriting'},
  'Ledger': {'category': 'Serif'},
  'Lekton': {'category': 'Sans Serif'},
  'Lemon': {'category': 'Display'},
  'Lemonada': {'category': 'Display'},
  'Libre Baskerville': {'category': 'Serif'},
  'Libre Franklin': {'category': 'Sans Serif'},
  'Life Savers': {'category': 'Display'},
  'Lilita One': {'category': 'Display'},
  'Lily Script One': {'category': 'Display'},
  'Limelight': {'category': 'Display'},
  'Linden Hill': {'category': 'Serif'},
  'Lobster': {'category': 'Display'},
  'Lobster Two': {'category': 'Display'},
  'Londrina Outline': {'category': 'Display'},
  'Londrina Shadow': {'category': 'Display'},
  'Londrina Sketch': {'category': 'Display'},
  'Londrina Solid': {'category': 'Display'},
  'Lora': {'category': 'Serif'},
  'Love Ya Like A Sister': {'category': 'Display'},
  'Loved by the King': {'category': 'Handwriting'},
  'Lovers Quarrel': {'category': 'Handwriting'},
  'Luckiest Guy': {'category': 'Display'},
  'Lusitana': {'category': 'Serif'},
  'Lustria': {'category': 'Serif'},
  'Macondo': {'category': 'Display'},
  'Macondo Swash Caps': {'category': 'Display'},
  'Mada': {'category': 'Sans Serif'},
  'Magra': {'category': 'Sans Serif'},
  'Maiden Orange': {'category': 'Display'},
  'Maitree': {'category': 'Serif'},
  'Mako': {'category': 'Sans Serif'},
  'Mallanna': {'category': 'Sans Serif'},
  'Mandali': {'category': 'Sans Serif'},
  'Marcellus': {'category': 'Serif'},
  'Marcellus SC': {'category': 'Serif'},
  'Marck Script': {'category': 'Handwriting'},
  'Margarine': {'category': 'Display'},
  'Marko One': {'category': 'Serif'},
  'Marmelad': {'category': 'Sans Serif'},
  'Martel': {'category': 'Serif'},
  'Martel Sans': {'category': 'Sans Serif'},
  'Marvel': {'category': 'Sans Serif'},
  'Mate': {'category': 'Serif'},
  'Mate SC': {'category': 'Serif'},
  'Maven Pro': {'category': 'Sans Serif'},
  'McLaren': {'category': 'Display'},
  'Meddon': {'category': 'Handwriting'},
  'MedievalSharp': {'category': 'Display'},
  'Medula One': {'category': 'Display'},
  'Meera Inimai': {'category': 'Sans Serif'},
  'Megrim': {'category': 'Display'},
  'Meie Script': {'category': 'Handwriting'},
  'Merienda': {'category': 'Handwriting'},
  'Merienda One': {'category': 'Handwriting'},
  'Merriweather': {'category': 'Serif'},
  'Merriweather Sans': {'category': 'Sans Serif'},
  'Metal': {'category': 'Display'},
  'Metal Mania': {'category': 'Display'},
  'Metamorphous': {'category': 'Display'},
  'Metrophobic': {'category': 'Sans Serif'},
  'Michroma': {'category': 'Sans Serif'},
  'Milonga': {'category': 'Display'},
  'Miltonian': {'category': 'Display'},
  'Miltonian Tattoo': {'category': 'Display'},
  'Miniver': {'category': 'Display'},
  'Miriam Libre': {'category': 'Sans Serif'},
  'Mirza': {'category': 'Display'},
  'Miss Fajardose': {'category': 'Handwriting'},
  'Mitr': {'category': 'Sans Serif'},
  'Modak': {'category': 'Display'},
  'Modern Antiqua': {'category': 'Display'},
  'Mogra': {'category': 'Display'},
  'Molengo': {'category': 'Sans Serif'},
  'Molle': {'category': 'Handwriting'},
  'Monda': {'category': 'Sans Serif'},
  'Monofett': {'category': 'Display'},
  'Monoton': {'category': 'Display'},
  'Monsieur La Doulaise': {'category': 'Handwriting'},
  'Montaga': {'category': 'Serif'},
  'Montez': {'category': 'Handwriting'},
  'Montserrat': {'category': 'Sans Serif'},
  'Montserrat Alternates': {'category': 'Sans Serif'},
  'Montserrat Subrayada': {'category': 'Sans Serif'},
  'Moul': {'category': 'Display'},
  'Moulpali': {'category': 'Display'},
  'Mountains of Christmas': {'category': 'Display'},
  'Mouse Memoirs': {'category': 'Sans Serif'},
  'Mr Bedfort': {'category': 'Handwriting'},
  'Mr Dafoe': {'category': 'Handwriting'},
  'Mr De Haviland': {'category': 'Handwriting'},
  'Mrs Saint Delafield': {'category': 'Handwriting'},
  'Mrs Sheppards': {'category': 'Handwriting'},
  'Mukta Vaani': {'category': 'Sans Serif'},
  'Muli': {'category': 'Sans Serif'},
  'Mystery Quest': {'category': 'Display'},
  'NTR': {'category': 'Sans Serif'},
  'Neucha': {'category': 'Handwriting'},
  'Neuton': {'category': 'Serif'},
  'New Rocker': {'category': 'Display'},
  'News Cycle': {'category': 'Sans Serif'},
  'Niconne': {'category': 'Handwriting'},
  'Nixie One': {'category': 'Display'},
  'Nobile': {'category': 'Sans Serif'},
  'Nokora': {'category': 'Serif'},
  'Norican': {'category': 'Handwriting'},
  'Nosifer': {'category': 'Display'},
  'Nothing You Could Do': {'category': 'Handwriting'},
  'Noticia Text': {'category': 'Serif'},
  'Noto Sans': {'category': 'Sans Serif'},
  'Noto Serif': {'category': 'Serif'},
  'Nova Cut': {'category': 'Display'},
  'Nova Flat': {'category': 'Display'},
  'Nova Mono': {'category': 'Monospace'},
  'Nova Oval': {'category': 'Display'},
  'Nova Round': {'category': 'Display'},
  'Nova Script': {'category': 'Display'},
  'Nova Slim': {'category': 'Display'},
  'Nova Square': {'category': 'Display'},
  'Numans': {'category': 'Sans Serif'},
  'Nunito': {'category': 'Sans Serif'},
  'Nunito Sans': {'category': 'Sans Serif'},
  'Odor Mean Chey': {'category': 'Display'},
  'Offside': {'category': 'Display'},
  'Old Standard TT': {'category': 'Serif'},
  'Oldenburg': {'category': 'Display'},
  'Oleo Script': {'category': 'Display'},
  'Oleo Script Swash Caps': {'category': 'Display'},
  'Open Sans': {'category': 'Sans Serif'},
  'Open Sans Condensed': {'category': 'Sans Serif'},
  'Oranienbaum': {'category': 'Serif'},
  'Orbitron': {'category': 'Sans Serif'},
  'Oregano': {'category': 'Display'},
  'Orienta': {'category': 'Sans Serif'},
  'Original Surfer': {'category': 'Display'},
  'Oswald': {'category': 'Sans Serif'},
  'Over the Rainbow': {'category': 'Handwriting'},
  'Overlock': {'category': 'Display'},
  'Overlock SC': {'category': 'Display'},
  'Overpass': {'category': 'Sans Serif'},
  'Overpass Mono': {'category': 'Monospace'},
  'Ovo': {'category': 'Serif'},
  'Oxygen': {'category': 'Sans Serif'},
  'Oxygen Mono': {'category': 'Monospace'},
  'PT Mono': {'category': 'Monospace'},
  'PT Sans': {'category': 'Sans Serif'},
  'PT Sans Caption': {'category': 'Sans Serif'},
  'PT Sans Narrow': {'category': 'Sans Serif'},
  'PT Serif': {'category': 'Serif'},
  'PT Serif Caption': {'category': 'Serif'},
  'Pacifico': {'category': 'Handwriting'},
  'Padauk': {'category': 'Sans Serif'},
  'Palanquin': {'category': 'Sans Serif'},
  'Palanquin Dark': {'category': 'Sans Serif'},
  'Pangolin': {'category': 'Handwriting'},
  'Paprika': {'category': 'Display'},
  'Parisienne': {'category': 'Handwriting'},
  'Passero One': {'category': 'Display'},
  'Passion One': {'category': 'Display'},
  'Pathway Gothic One': {'category': 'Sans Serif'},
  'Patrick Hand': {'category': 'Handwriting'},
  'Patrick Hand SC': {'category': 'Handwriting'},
  'Pattaya': {'category': 'Sans Serif'},
  'Patua One': {'category': 'Display'},
  'Pavanam': {'category': 'Sans Serif'},
  'Paytone One': {'category': 'Sans Serif'},
  'Peddana': {'category': 'Serif'},
  'Peralta': {'category': 'Display'},
  'Permanent Marker': {'category': 'Handwriting'},
  'Petit Formal Script': {'category': 'Handwriting'},
  'Petrona': {'category': 'Serif'},
  'Philosopher': {'category': 'Sans Serif'},
  'Piedra': {'category': 'Display'},
  'Pinyon Script': {'category': 'Handwriting'},
  'Pirata One': {'category': 'Display'},
  'Plaster': {'category': 'Display'},
  'Play': {'category': 'Sans Serif'},
  'Playball': {'category': 'Display'},
  'Playfair Display': {'category': 'Serif'},
  'Playfair Display SC': {'category': 'Serif'},
  'Podkova': {'category': 'Serif'},
  'Poiret One': {'category': 'Display'},
  'Poller One': {'category': 'Display'},
  'Poly': {'category': 'Serif'},
  'Pompiere': {'category': 'Display'},
  'Pontano Sans': {'category': 'Sans Serif'},
  'Poppins': {'category': 'Sans Serif'},
  'Port Lligat Sans': {'category': 'Sans Serif'},
  'Port Lligat Slab': {'category': 'Serif'},
  'Pragati Narrow': {'category': 'Sans Serif'},
  'Prata': {'category': 'Serif'},
  'Preahvihear': {'category': 'Display'},
  'Press Start 2P': {'category': 'Display'},
  'Pridi': {'category': 'Serif'},
  'Princess Sofia': {'category': 'Handwriting'},
  'Prociono': {'category': 'Serif'},
  'Prompt': {'category': 'Sans Serif'},
  'Prosto One': {'category': 'Display'},
  'Proza Libre': {'category': 'Sans Serif'},
  'Puritan': {'category': 'Sans Serif'},
  'Purple Purse': {'category': 'Display'},
  'Quando': {'category': 'Serif'},
  'Quantico': {'category': 'Sans Serif'},
  'Quattrocento': {'category': 'Serif'},
  'Quattrocento Sans': {'category': 'Sans Serif'},
  'Questrial': {'category': 'Sans Serif'},
  'Quicksand': {'category': 'Sans Serif'},
  'Quintessential': {'category': 'Handwriting'},
  'Qwigley': {'category': 'Handwriting'},
  'Racing Sans One': {'category': 'Display'},
  'Radley': {'category': 'Serif'},
  'Rajdhani': {'category': 'Sans Serif'},
  'Rakkas': {'category': 'Display'},
  'Raleway': {'category': 'Sans Serif'},
  'Raleway Dots': {'category': 'Display'},
  'Ramabhadra': {'category': 'Sans Serif'},
  'Ramaraja': {'category': 'Serif'},
  'Rambla': {'category': 'Sans Serif'},
  'Rammetto One': {'category': 'Display'},
  'Ranchers': {'category': 'Display'},
  'Rancho': {'category': 'Handwriting'},
  'Ranga': {'category': 'Display'},
  'Rasa': {'category': 'Serif'},
  'Rationale': {'category': 'Sans Serif'},
  'Ravi Prakash': {'category': 'Display'},
  'Redressed': {'category': 'Handwriting'},
  'Reem Kufi': {'category': 'Sans Serif'},
  'Reenie Beanie': {'category': 'Handwriting'},
  'Revalia': {'category': 'Display'},
  'Rhodium Libre': {'category': 'Serif'},
  'Ribeye': {'category': 'Display'},
  'Ribeye Marrow': {'category': 'Display'},
  'Righteous': {'category': 'Display'},
  'Risque': {'category': 'Display'},
  'Roboto': {'category': 'Sans Serif'},
  'Roboto Condensed': {'category': 'Sans Serif'},
  'Roboto Mono': {'category': 'Monospace'},
  'Roboto Slab': {'category': 'Serif'},
  'Rochester': {'category': 'Handwriting'},
  'Rock Salt': {'category': 'Handwriting'},
  'Rokkitt': {'category': 'Serif'},
  'Romanesco': {'category': 'Handwriting'},
  'Ropa Sans': {'category': 'Sans Serif'},
  'Rosario': {'category': 'Sans Serif'},
  'Rosarivo': {'category': 'Serif'},
  'Rouge Script': {'category': 'Handwriting'},
  'Rozha One': {'category': 'Serif'},
  'Rubik': {'category': 'Sans Serif'},
  'Rubik Mono One': {'category': 'Sans Serif'},
  'Ruda': {'category': 'Sans Serif'},
  'Rufina': {'category': 'Serif'},
  'Ruge Boogie': {'category': 'Handwriting'},
  'Ruluko': {'category': 'Sans Serif'},
  'Rum Raisin': {'category': 'Sans Serif'},
  'Ruslan Display': {'category': 'Display'},
  'Russo One': {'category': 'Sans Serif'},
  'Ruthie': {'category': 'Handwriting'},
  'Rye': {'category': 'Display'},
  'Sacramento': {'category': 'Handwriting'},
  'Sahitya': {'category': 'Serif'},
  'Sail': {'category': 'Display'},
  'Salsa': {'category': 'Display'},
  'Sanchez': {'category': 'Serif'},
  'Sancreek': {'category': 'Display'},
  'Sansita': {'category': 'Sans Serif'},
  'Sansita One': {'category': 'Display'},
  'Sarala': {'category': 'Sans Serif'},
  'Sarina': {'category': 'Display'},
  'Sarpanch': {'category': 'Sans Serif'},
  'Satisfy': {'category': 'Handwriting'},
  'Scada': {'category': 'Sans Serif'},
  'Scheherazade': {'category': 'Serif'},
  'Schoolbell': {'category': 'Handwriting'},
  'Scope One': {'category': 'Serif'},
  'Seaweed Script': {'category': 'Display'},
  'Secular One': {'category': 'Sans Serif'},
  'Sevillana': {'category': 'Display'},
  'Seymour One': {'category': 'Sans Serif'},
  'Shadows Into Light': {'category': 'Handwriting'},
  'Shadows Into Light Two': {'category': 'Handwriting'},
  'Shanti': {'category': 'Sans Serif'},
  'Share': {'category': 'Display'},
  'Share Tech': {'category': 'Sans Serif'},
  'Share Tech Mono': {'category': 'Monospace'},
  'Shojumaru': {'category': 'Display'},
  'Short Stack': {'category': 'Handwriting'},
  'Shrikhand': {'category': 'Display'},
  'Siemreap': {'category': 'Display'},
  'Sigmar One': {'category': 'Display'},
  'Signika': {'category': 'Sans Serif'},
  'Signika Negative': {'category': 'Sans Serif'},
  'Simonetta': {'category': 'Display'},
  'Sintony': {'category': 'Sans Serif'},
  'Sirin Stencil': {'category': 'Display'},
  'Six Caps': {'category': 'Sans Serif'},
  'Skranji': {'category': 'Display'},
  'Slabo 13px': {'category': 'Serif'},
  'Slabo 27px': {'category': 'Serif'},
  'Slackey': {'category': 'Display'},
  'Smokum': {'category': 'Display'},
  'Smythe': {'category': 'Display'},
  'Sniglet': {'category': 'Display'},
  'Snippet': {'category': 'Sans Serif'},
  'Snowburst One': {'category': 'Display'},
  'Sofadi One': {'category': 'Display'},
  'Sofia': {'category': 'Handwriting'},
  'Sonsie One': {'category': 'Display'},
  'Sorts Mill Goudy': {'category': 'Serif'},
  'Source Code Pro': {'category': 'Monospace'},
  'Source Sans Pro': {'category': 'Sans Serif'},
  'Source Serif Pro': {'category': 'Serif'},
  'Space Mono': {'category': 'Monospace'},
  'Special Elite': {'category': 'Display'},
  'Spicy Rice': {'category': 'Display'},
  'Spinnaker': {'category': 'Sans Serif'},
  'Spirax': {'category': 'Display'},
  'Squada One': {'category': 'Display'},
  'Sree Krushnadevaraya': {'category': 'Serif'},
  'Sriracha': {'category': 'Handwriting'},
  'Stalemate': {'category': 'Handwriting'},
  'Stalinist One': {'category': 'Display'},
  'Stardos Stencil': {'category': 'Display'},
  'Stint Ultra Condensed': {'category': 'Display'},
  'Stint Ultra Expanded': {'category': 'Display'},
  'Stoke': {'category': 'Serif'},
  'Strait': {'category': 'Sans Serif'},
  'Sue Ellen Francisco': {'category': 'Handwriting'},
  'Suez One': {'category': 'Serif'},
  'Sumana': {'category': 'Serif'},
  'Sunshiney': {'category': 'Handwriting'},
  'Supermercado One': {'category': 'Display'},
  'Sura': {'category': 'Serif'},
  'Suranna': {'category': 'Serif'},
  'Suravaram': {'category': 'Serif'},
  'Suwannaphum': {'category': 'Display'},
  'Swanky and Moo Moo': {'category': 'Handwriting'},
  'Syncopate': {'category': 'Sans Serif'},
  'Tangerine': {'category': 'Handwriting'},
  'Taprom': {'category': 'Display'},
  'Tauri': {'category': 'Sans Serif'},
  'Taviraj': {'category': 'Serif'},
  'Teko': {'category': 'Sans Serif'},
  'Telex': {'category': 'Sans Serif'},
  'Tenali Ramakrishna': {'category': 'Sans Serif'},
  'Tenor Sans': {'category': 'Sans Serif'},
  'Text Me One': {'category': 'Sans Serif'},
  'The Girl Next Door': {'category': 'Handwriting'},
  'Tienne': {'category': 'Serif'},
  'Tillana': {'category': 'Handwriting'},
  'Timmana': {'category': 'Sans Serif'},
  'Tinos': {'category': 'Serif'},
  'Titan One': {'category': 'Display'},
  'Titillium Web': {'category': 'Sans Serif'},
  'Trade Winds': {'category': 'Display'},
  'Trirong': {'category': 'Serif'},
  'Trocchi': {'category': 'Serif'},
  'Trochut': {'category': 'Display'},
  'Trykker': {'category': 'Serif'},
  'Tulpen One': {'category': 'Display'},
  'Ubuntu': {'category': 'Sans Serif'},
  'Ubuntu Condensed': {'category': 'Sans Serif'},
  'Ubuntu Mono': {'category': 'Monospace'},
  'Ultra': {'category': 'Serif'},
  'Uncial Antiqua': {'category': 'Display'},
  'Underdog': {'category': 'Display'},
  'Unica One': {'category': 'Display'},
  'UnifrakturCook': {'category': 'Display'},
  'UnifrakturMaguntia': {'category': 'Display'},
  'Unkempt': {'category': 'Display'},
  'Unlock': {'category': 'Display'},
  'Unna': {'category': 'Serif'},
  'VT323': {'category': 'Monospace'},
  'Vampiro One': {'category': 'Display'},
  'Varela': {'category': 'Sans Serif'},
  'Varela Round': {'category': 'Sans Serif'},
  'Vast Shadow': {'category': 'Display'},
  'Vesper Libre': {'category': 'Serif'},
  'Vibur': {'category': 'Handwriting'},
  'Vidaloka': {'category': 'Serif'},
  'Viga': {'category': 'Sans Serif'},
  'Voces': {'category': 'Display'},
  'Volkhov': {'category': 'Serif'},
  'Vollkorn': {'category': 'Serif'},
  'Voltaire': {'category': 'Sans Serif'},
  'Waiting for the Sunrise': {'category': 'Handwriting'},
  'Wallpoet': {'category': 'Display'},
  'Walter Turncoat': {'category': 'Handwriting'},
  'Warnes': {'category': 'Display'},
  'Wellfleet': {'category': 'Display'},
  'Wendy One': {'category': 'Sans Serif'},
  'Wire One': {'category': 'Sans Serif'},
  'Work Sans': {'category': 'Sans Serif'},
  'Yanone Kaffeesatz': {'category': 'Sans Serif'},
  'Yantramanav': {'category': 'Sans Serif'},
  'Yatra One': {'category': 'Display'},
  'Yellowtail': {'category': 'Handwriting'},
  'Yeseva One': {'category': 'Display'},
  'Yesteryear': {'category': 'Handwriting'},
  'Yrsa': {'category': 'Serif'},
  'Zeyada': {'category': 'Handwriting'}
};

export const fonts = {
  safe: fontsSafe,
  google: fontsGoogle,
};

export const resolveProvider = (name) => {
  return findKey(fonts, (fontList) => {
    return typeof fontList[name] === 'object';
  });
};

/**
 * Is this a safe font?
 *
 * @param font
 * @return bool
 */
export const isSafe = font => (typeof fonts.safe[font] === 'object');

/**
 * Get the fallback fonts
 *
 * @param name
 * @param all
 * @returns {Array}
 */
export const getFallbackFonts = (name, all = []) => {
  const provider = resolveProvider(name);

  if (provider) {
    const definition = fonts[provider][name];
    if (typeof definition.fallback !== 'undefined') {
      all = definition.fallback;
    } else {
      // use the category to lookup the fonts
      all = all.concat(categories[definition.category].fallback);
    }
  }

  return all;
};

/**
 * Get the font for css
 *
 * @param name
 * @param include
 * @returns {*}
 */
export const getFontForCSS = (name, include = [ name ]) => {
  const all = getFallbackFonts(name, include);
  
  return all.map((font) => font.search(' ') !== -1 ? `'${font}'` : font)
    .join(',');
};

export default {
  google: fontsGoogle,
};
